spring.application.name=bff-client
server.port=8080

# ==================================
# Mutual TLS handshake connection
# ==================================
server.ssl.enabled=true

# Postman -- HTTPs --> BFF as server
server.ssl.key-store=file:certs/bff/bff-server-keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${BFF_SERVER_KEYSTORE_PASSWORD}
server.ssl.key-alias=bff-server
key-store.path=certs/bff/bff-client-keystore.p12

# BFF as a client -- HTTPs --> Driver as server
client.ssl.key-store=file:certs/bff/bff-client-keystore.p12
client.ssl.key-store-type=PKCS12
client.ssl.key-store-password=${BFF_CLIENT_KEYSTORE_PASSWORD}
client.ssl.key-alias=bff-client

server.ssl.trust-store=file:certs/bff/bff-truststore.p12
server.ssl.trust-store-type=PKCS12
server.ssl.trust-store-password=${BFF_TRUSTSTORE_PASSWORD}
server.ssl.trust-store-alias=internal-ca
truststore.path=certs/bff/bff-truststore.p12

# =================================
# Cognito OAuth2 Client Credentials
# =================================
spring.security.oauth2.client.registration.driver-service.client-id=${DRIVER_M2M_CLIENT_ID}
spring.security.oauth2.client.registration.driver-service.client-secret=${DRIVER_M2M_CLIENT_SECRET}
spring.security.oauth2.client.registration.driver-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.driver-service.scope=default-m2m-resource-server-tpzpjc/read
spring.security.oauth2.client.registration.driver-service.provider=cognito
spring.security.oauth2.client.provider.cognito.token-uri=https://ap-southeast-1hlzj5ixwc.auth.ap-southeast-1.amazoncognito.com/oauth2/token

# ==================================
# Cognito OAuth2 Resource Server
# ==================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_hLZj5IXWc

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.oauth2.client=TRACE
logging.level.org.springframework.security.oauth2.core=TRACE

# ==============================
# Eureka server registered
# ==============================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# ============================================
# Consuming Driver by Eureka discovery
# =============================================
driver.service.base-url=https://driver-service:8082
